// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "model.accounts-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // date_fields
  //

  bool access::composite_value_traits< ::model::accounts::date_fields, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // created_
    //
    t[0UL] = 0;

    // updated_
    //
    t[1UL] = 0;

    // deleted_
    //
    t[2UL] = 0;

    return grew;
  }

  void access::composite_value_traits< ::model::accounts::date_fields, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (b);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);
    ODB_POTENTIALLY_UNUSED (n);

    // created_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.created_value;
    b[n].is_null = &i.created_null;
    n++;

    // updated_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.updated_value;
    b[n].is_null = &i.updated_null;
    n++;

    // deleted_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.deleted_value;
    b[n].is_null = &i.deleted_null;
    n++;
  }

  bool access::composite_value_traits< ::model::accounts::date_fields, id_mysql >::
  init (image_type& i,
        const value_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // created_
    //
    {
      ::time_t const& v =
        o.created_;

      bool is_null (false);
      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_image (
        i.created_value, is_null, v);
      i.created_null = is_null;
    }

    // updated_
    //
    {
      ::time_t const& v =
        o.updated_;

      bool is_null (true);
      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_image (
        i.updated_value, is_null, v);
      i.updated_null = is_null;
    }

    // deleted_
    //
    {
      ::time_t const& v =
        o.deleted_;

      bool is_null (true);
      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_image (
        i.deleted_value, is_null, v);
      i.deleted_null = is_null;
    }

    return grew;
  }

  void access::composite_value_traits< ::model::accounts::date_fields, id_mysql >::
  init (value_type& o,
        const image_type&  i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // created_
    //
    {
      ::time_t& v =
        o.created_;

      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_value (
        v,
        i.created_value,
        i.created_null);
    }

    // updated_
    //
    {
      ::time_t& v =
        o.updated_;

      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_value (
        v,
        i.updated_value,
        i.updated_null);
    }

    // deleted_
    //
    {
      ::time_t& v =
        o.deleted_;

      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_value (
        v,
        i.deleted_value,
        i.deleted_null);
    }
  }

  // session
  //

  bool access::composite_value_traits< ::model::accounts::session, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // session_
    //
    if (t[0UL])
    {
      i.session_value.capacity (i.session_size);
      grew = true;
    }

    // sessionTime_
    //
    t[1UL] = 0;

    return grew;
  }

  void access::composite_value_traits< ::model::accounts::session, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (b);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);
    ODB_POTENTIALLY_UNUSED (n);

    // session_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.session_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.session_value.capacity ());
    b[n].length = &i.session_size;
    b[n].is_null = &i.session_null;
    n++;

    // sessionTime_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.sessionTime_value;
    b[n].is_null = &i.sessionTime_null;
    n++;
  }

  bool access::composite_value_traits< ::model::accounts::session, id_mysql >::
  init (image_type& i,
        const value_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // session_
    //
    {
      ::std::string const& v =
        o.session_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.session_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.session_value,
        size,
        is_null,
        v);
      i.session_null = is_null;
      i.session_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.session_value.capacity ());
    }

    // sessionTime_
    //
    {
      ::time_t const& v =
        o.sessionTime_;

      bool is_null (false);
      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_image (
        i.sessionTime_value, is_null, v);
      i.sessionTime_null = is_null;
    }

    return grew;
  }

  void access::composite_value_traits< ::model::accounts::session, id_mysql >::
  init (value_type& o,
        const image_type&  i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // session_
    //
    {
      ::std::string& v =
        o.session_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.session_value,
        i.session_size,
        i.session_null);
    }

    // sessionTime_
    //
    {
      ::time_t& v =
        o.sessionTime_;

      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_value (
        v,
        i.sessionTime_value,
        i.sessionTime_null);
    }
  }

  // account
  //

  struct access::object_traits_impl< ::model::accounts::account, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::model::accounts::account, id_mysql >::id_type
  access::object_traits_impl< ::model::accounts::account, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::model::accounts::account, id_mysql >::id_type
  access::object_traits_impl< ::model::accounts::account, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::model::accounts::account, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = 0;

    // email_
    //
    if (t[1UL])
    {
      i.email_value.capacity (i.email_size);
      grew = true;
    }

    // email_verified_
    //
    t[2UL] = 0;

    // sms_
    //
    if (t[3UL])
    {
      i.sms_value.capacity (i.sms_size);
      grew = true;
    }

    // sms_status_
    //
    if (t[4UL])
    {
      if (mysql::enum_traits::grow (i.sms_status_value, i.sms_status_size))
        grew = true;
      else
        t[4UL] = 0;
    }

    // first_name_
    //
    if (t[5UL])
    {
      i.first_name_value.capacity (i.first_name_size);
      grew = true;
    }

    // surname_
    //
    if (t[6UL])
    {
      i.surname_value.capacity (i.surname_size);
      grew = true;
    }

    // dob_
    //
    t[7UL] = 0;

    // notes_
    //
    if (t[8UL])
    {
      i.notes_value.capacity (i.notes_size);
      grew = true;
    }

    // password_
    //
    if (t[9UL])
    {
      i.password_value.capacity (i.password_size);
      grew = true;
    }

    // status_
    //
    if (t[10UL])
    {
      if (mysql::enum_traits::grow (i.status_value, i.status_size))
        grew = true;
      else
        t[10UL] = 0;
    }

    // email_status_
    //
    if (t[11UL])
    {
      if (mysql::enum_traits::grow (i.email_status_value, i.email_status_size))
        grew = true;
      else
        t[11UL] = 0;
    }

    // email_contact_status_
    //
    if (t[12UL])
    {
      if (mysql::enum_traits::grow (i.email_contact_status_value, i.email_contact_status_size))
        grew = true;
      else
        t[12UL] = 0;
    }

    // session_
    //
    if (composite_value_traits< ::model::accounts::session, id_mysql >::grow (
          i.session_value, t + 13UL))
      grew = true;

    // dates_
    //
    if (composite_value_traits< ::model::accounts::date_fields, id_mysql >::grow (
          i.dates_value, t + 15UL))
      grew = true;

    return grew;
  }

  void access::object_traits_impl< ::model::accounts::account, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // email_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.email_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.email_value.capacity ());
    b[n].length = &i.email_size;
    b[n].is_null = &i.email_null;
    n++;

    // email_verified_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.email_verified_value;
    b[n].is_null = &i.email_verified_null;
    n++;

    // sms_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.sms_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.sms_value.capacity ());
    b[n].length = &i.sms_size;
    b[n].is_null = &i.sms_null;
    n++;

    // sms_status_
    //
    mysql::enum_traits::bind (b[n],
                              i.sms_status_value,
                              i.sms_status_size,
                              &i.sms_status_null);
    n++;

    // first_name_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.first_name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.first_name_value.capacity ());
    b[n].length = &i.first_name_size;
    b[n].is_null = &i.first_name_null;
    n++;

    // surname_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.surname_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.surname_value.capacity ());
    b[n].length = &i.surname_size;
    b[n].is_null = &i.surname_null;
    n++;

    // dob_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.dob_value;
    b[n].is_null = &i.dob_null;
    n++;

    // notes_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.notes_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.notes_value.capacity ());
    b[n].length = &i.notes_size;
    b[n].is_null = &i.notes_null;
    n++;

    // password_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.password_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.password_value.capacity ());
    b[n].length = &i.password_size;
    b[n].is_null = &i.password_null;
    n++;

    // status_
    //
    mysql::enum_traits::bind (b[n],
                              i.status_value,
                              i.status_size,
                              &i.status_null);
    n++;

    // email_status_
    //
    mysql::enum_traits::bind (b[n],
                              i.email_status_value,
                              i.email_status_size,
                              &i.email_status_null);
    n++;

    // email_contact_status_
    //
    mysql::enum_traits::bind (b[n],
                              i.email_contact_status_value,
                              i.email_contact_status_size,
                              &i.email_contact_status_null);
    n++;

    // session_
    //
    composite_value_traits< ::model::accounts::session, id_mysql >::bind (
      b + n, i.session_value, sk);
    n += 2UL;

    // dates_
    //
    composite_value_traits< ::model::accounts::date_fields, id_mysql >::bind (
      b + n, i.dates_value, sk);
    n += 3UL;
  }

  void access::object_traits_impl< ::model::accounts::account, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::model::accounts::account, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // id_
    //
    if (sk == statement_insert)
    {
      long unsigned int const& v =
        o.id_;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, v);
      i.id_null = is_null;
    }

    // email_
    //
    {
      ::std::string const& v =
        o.email_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.email_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.email_value,
        size,
        is_null,
        v);
      i.email_null = is_null;
      i.email_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.email_value.capacity ());
    }

    // email_verified_
    //
    {
      ::time_t const& v =
        o.email_verified_;

      bool is_null (false);
      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_image (
        i.email_verified_value, is_null, v);
      i.email_verified_null = is_null;
    }

    // sms_
    //
    {
      ::std::string const& v =
        o.sms_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.sms_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.sms_value,
        size,
        is_null,
        v);
      i.sms_null = is_null;
      i.sms_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.sms_value.capacity ());
    }

    // sms_status_
    //
    {
      ::model::accounts::SMSStatus const& v =
        o.sms_status_;

      bool is_null (false);
      if (mysql::enum_traits::set_image (
            i.sms_status_value,
            i.sms_status_size,
            is_null,
            v))
        grew = true;

      i.sms_status_null = is_null;
    }

    // first_name_
    //
    {
      ::std::string const& v =
        o.first_name_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.first_name_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.first_name_value,
        size,
        is_null,
        v);
      i.first_name_null = is_null;
      i.first_name_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.first_name_value.capacity ());
    }

    // surname_
    //
    {
      ::std::string const& v =
        o.surname_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.surname_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.surname_value,
        size,
        is_null,
        v);
      i.surname_null = is_null;
      i.surname_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.surname_value.capacity ());
    }

    // dob_
    //
    {
      ::time_t const& v =
        o.dob_;

      bool is_null (false);
      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_image (
        i.dob_value, is_null, v);
      i.dob_null = is_null;
    }

    // notes_
    //
    {
      ::std::string const& v =
        o.notes_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.notes_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.notes_value,
        size,
        is_null,
        v);
      i.notes_null = is_null;
      i.notes_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.notes_value.capacity ());
    }

    // password_
    //
    {
      ::std::string const& v =
        o.password_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.password_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.password_value,
        size,
        is_null,
        v);
      i.password_null = is_null;
      i.password_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.password_value.capacity ());
    }

    // status_
    //
    {
      ::model::accounts::AccountStatus const& v =
        o.status_;

      bool is_null (false);
      if (mysql::enum_traits::set_image (
            i.status_value,
            i.status_size,
            is_null,
            v))
        grew = true;

      i.status_null = is_null;
    }

    // email_status_
    //
    {
      ::model::accounts::EmailStatus const& v =
        o.email_status_;

      bool is_null (false);
      if (mysql::enum_traits::set_image (
            i.email_status_value,
            i.email_status_size,
            is_null,
            v))
        grew = true;

      i.email_status_null = is_null;
    }

    // email_contact_status_
    //
    {
      ::model::accounts::EmailContact const& v =
        o.email_contact_status_;

      bool is_null (false);
      if (mysql::enum_traits::set_image (
            i.email_contact_status_value,
            i.email_contact_status_size,
            is_null,
            v))
        grew = true;

      i.email_contact_status_null = is_null;
    }

    // session_
    //
    {
      ::model::accounts::session const& v =
        o.session_;

      if (composite_value_traits< ::model::accounts::session, id_mysql >::init (
            i.session_value,
            v,
            sk))
        grew = true;
    }

    // dates_
    //
    {
      ::model::accounts::date_fields const& v =
        o.dates_;

      composite_value_traits< ::model::accounts::date_fields, id_mysql >::init (
        i.dates_value,
        v,
        sk);
    }

    return grew;
  }

  void access::object_traits_impl< ::model::accounts::account, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      long unsigned int& v =
        o.id_;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // email_
    //
    {
      ::std::string& v =
        o.email_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.email_value,
        i.email_size,
        i.email_null);
    }

    // email_verified_
    //
    {
      ::time_t& v =
        o.email_verified_;

      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_value (
        v,
        i.email_verified_value,
        i.email_verified_null);
    }

    // sms_
    //
    {
      ::std::string& v =
        o.sms_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.sms_value,
        i.sms_size,
        i.sms_null);
    }

    // sms_status_
    //
    {
      ::model::accounts::SMSStatus& v =
        o.sms_status_;

      mysql::enum_traits::set_value (
        v,
        i.sms_status_value,
        i.sms_status_size,
        i.sms_status_null);
    }

    // first_name_
    //
    {
      ::std::string& v =
        o.first_name_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.first_name_value,
        i.first_name_size,
        i.first_name_null);
    }

    // surname_
    //
    {
      ::std::string& v =
        o.surname_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.surname_value,
        i.surname_size,
        i.surname_null);
    }

    // dob_
    //
    {
      ::time_t& v =
        o.dob_;

      mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::set_value (
        v,
        i.dob_value,
        i.dob_null);
    }

    // notes_
    //
    {
      ::std::string& v =
        o.notes_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.notes_value,
        i.notes_size,
        i.notes_null);
    }

    // password_
    //
    {
      ::std::string& v =
        o.password_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.password_value,
        i.password_size,
        i.password_null);
    }

    // status_
    //
    {
      ::model::accounts::AccountStatus& v =
        o.status_;

      mysql::enum_traits::set_value (
        v,
        i.status_value,
        i.status_size,
        i.status_null);
    }

    // email_status_
    //
    {
      ::model::accounts::EmailStatus& v =
        o.email_status_;

      mysql::enum_traits::set_value (
        v,
        i.email_status_value,
        i.email_status_size,
        i.email_status_null);
    }

    // email_contact_status_
    //
    {
      ::model::accounts::EmailContact& v =
        o.email_contact_status_;

      mysql::enum_traits::set_value (
        v,
        i.email_contact_status_value,
        i.email_contact_status_size,
        i.email_contact_status_null);
    }

    // session_
    //
    {
      ::model::accounts::session& v =
        o.session_;

      composite_value_traits< ::model::accounts::session, id_mysql >::init (
        v,
        i.session_value,
        db);
    }

    // dates_
    //
    {
      ::model::accounts::date_fields& v =
        o.dates_;

      composite_value_traits< ::model::accounts::date_fields, id_mysql >::init (
        v,
        i.dates_value,
        db);
    }
  }

  void access::object_traits_impl< ::model::accounts::account, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::model::accounts::account, id_mysql >::persist_statement[] =
  "INSERT INTO `account` "
  "(`id`, "
  "`email`, "
  "`email_verified`, "
  "`sms`, "
  "`sms_status`, "
  "`first_name`, "
  "`surname`, "
  "`dob`, "
  "`notes`, "
  "`password`, "
  "`status`, "
  "`email_status`, "
  "`email_contact_status`, "
  "`session_session`, "
  "`session_sessionTime`, "
  "`dates_created`, "
  "`dates_updated`, "
  "`dates_deleted`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::model::accounts::account, id_mysql >::find_statement[] =
  "SELECT "
  "`account`.`id`, "
  "`account`.`email`, "
  "`account`.`email_verified`, "
  "`account`.`sms`, "
  "CONCAT(`account`.`sms_status`+0,' ',`account`.`sms_status`), "
  "`account`.`first_name`, "
  "`account`.`surname`, "
  "`account`.`dob`, "
  "`account`.`notes`, "
  "`account`.`password`, "
  "CONCAT(`account`.`status`+0,' ',`account`.`status`), "
  "CONCAT(`account`.`email_status`+0,' ',`account`.`email_status`), "
  "CONCAT(`account`.`email_contact_status`+0,' ',`account`.`email_contact_status`), "
  "`account`.`session_session`, "
  "`account`.`session_sessionTime`, "
  "`account`.`dates_created`, "
  "`account`.`dates_updated`, "
  "`account`.`dates_deleted` "
  "FROM `account` "
  "WHERE `account`.`id`=?";

  const char access::object_traits_impl< ::model::accounts::account, id_mysql >::update_statement[] =
  "UPDATE `account` "
  "SET "
  "`email`=?, "
  "`email_verified`=?, "
  "`sms`=?, "
  "`sms_status`=?, "
  "`first_name`=?, "
  "`surname`=?, "
  "`dob`=?, "
  "`notes`=?, "
  "`password`=?, "
  "`status`=?, "
  "`email_status`=?, "
  "`email_contact_status`=?, "
  "`session_session`=?, "
  "`session_sessionTime`=?, "
  "`dates_created`=?, "
  "`dates_updated`=?, "
  "`dates_deleted`=? "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::model::accounts::account, id_mysql >::erase_statement[] =
  "DELETE FROM `account` "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::model::accounts::account, id_mysql >::query_statement[] =
  "SELECT "
  "`account`.`id`, "
  "`account`.`email`, "
  "`account`.`email_verified`, "
  "`account`.`sms`, "
  "CONCAT(`account`.`sms_status`+0,' ',`account`.`sms_status`), "
  "`account`.`first_name`, "
  "`account`.`surname`, "
  "`account`.`dob`, "
  "`account`.`notes`, "
  "`account`.`password`, "
  "CONCAT(`account`.`status`+0,' ',`account`.`status`), "
  "CONCAT(`account`.`email_status`+0,' ',`account`.`email_status`), "
  "CONCAT(`account`.`email_contact_status`+0,' ',`account`.`email_contact_status`), "
  "`account`.`session_session`, "
  "`account`.`session_sessionTime`, "
  "`account`.`dates_created`, "
  "`account`.`dates_updated`, "
  "`account`.`dates_deleted` "
  "FROM `account`";

  const char access::object_traits_impl< ::model::accounts::account, id_mysql >::erase_query_statement[] =
  "DELETE FROM `account`";

  const char access::object_traits_impl< ::model::accounts::account, id_mysql >::table_name[] =
  "`account`";

  void access::object_traits_impl< ::model::accounts::account, id_mysql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.id_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::model::accounts::account, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::model::accounts::account, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::model::accounts::account, id_mysql >::pointer_type
  access::object_traits_impl< ::model::accounts::account, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::model::accounts::account, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::model::accounts::account, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::model::accounts::account, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::model::accounts::account, id_mysql >::object_type >
  access::object_traits_impl< ::model::accounts::account, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::model::accounts::account, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
